# Form implementation generated from reading ui file 'c:\Users\sergi\OneDrive\Documentos\UPIITA\4 Semestre\Programacion Avanzada\Practica6\Instrucciones.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(510, 466)
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 491, 391))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 489, 389))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(20, 10, 401, 371))
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Enciende el juego: Asegúrate de que el juego esté encendido y funcione correctamente. Si es necesario, ajusta el volumen a un nivel adecuado.\n"
"\n"
"Inicia el juego: Presiona el botón de inicio o el botón de encendido para comenzar una nueva partida.\n"
"\n"
"Observa la secuencia: El juego comenzará mostrando una secuencia de luces y sonidos. Presta atención a la secuencia, ya que tendrás que repetirla exactamente como la veas.\n"
"\n"
"Repite la secuencia: Después de que \"Simon\" muestre la secuencia, toca los botones o colores correspondientes en el mismo orden en que los viste y los escuchaste. Si lo haces correctamente, el juego te mostrará una nueva secuencia más larga.\n"
"\n"
"Continúa jugando: A medida que progresas, el juego se vuelve más desafiante al aumentar la longitud de las secuencias. Sigue repitiendo las secuencias con precisión.\n"
"\n"
"Errores: Si te equivocas al repetir una secuencia, el juego te indicará que cometiste un error, generalmente con una secuencia de sonidos especiales. Puedes intentarlo de nuevo desde el principio o elegir rendirte.\n"
"\n"
"Puntaje: El juego llevará un registro de tu puntaje, que corresponde a la cantidad de secuencias que has repetido correctamente. Intenta superar tu puntaje máximo anterior y desafía a tus amigos a hacerlo mejor.\n"
"\n"
"Final del juego: El juego continúa hasta que cometas un error o decidas detenerte. Puedes apagar el juego en cualquier momento.\n"
"\n"
"¡Diviértete jugando \"Simon Dice\" y desafía tu memoria y concentración para alcanzar secuencias más largas y puntajes más altos!"))
