# Form implementation generated from reading ui file 'c:\Users\sergi\OneDrive\Documentos\UPIITA\4 Semestre\Programacion Avanzada\Practica6\PrincipalSimon.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PrincipalSimon(object):
    def setupUi(self, PrincipalSimon):
        PrincipalSimon.setObjectName("PrincipalSimon")
        PrincipalSimon.resize(650, 536)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\sergi\\OneDrive\\Documentos\\UPIITA\\4 Semestre\\Programacion Avanzada\\Practica6\\logo.jpeg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PrincipalSimon.setWindowIcon(icon)
        PrincipalSimon.setStyleSheet("background-color: rgb(25, 25, 25);")
        self.centralwidget = QtWidgets.QWidget(parent=PrincipalSimon)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 300, 111, 81))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("border-radius: 40px;\n"
"font: 700 18pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 203, 0);")
        self.pushButton.setIconSize(QtCore.QSize(115, 141))
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 390, 241, 81))
        self.pushButton_2.setStyleSheet("border-radius: 40px;\n"
"font: 700 18pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 631, 221))
        self.label.setStyleSheet("border-image: url(:/simonsays.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("c:\\Users\\sergi\\OneDrive\\Documentos\\UPIITA\\4 Semestre\\Programacion Avanzada\\Practica6\\simonsays.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        PrincipalSimon.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=PrincipalSimon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 22))
        self.menubar.setObjectName("menubar")
        PrincipalSimon.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=PrincipalSimon)
        self.statusbar.setObjectName("statusbar")
        PrincipalSimon.setStatusBar(self.statusbar)

        self.retranslateUi(PrincipalSimon)
        QtCore.QMetaObject.connectSlotsByName(PrincipalSimon)

    def retranslateUi(self, PrincipalSimon):
        _translate = QtCore.QCoreApplication.translate
        PrincipalSimon.setWindowTitle(_translate("PrincipalSimon", "Simon Dice"))
        self.pushButton.setText(_translate("PrincipalSimon", "JUGAR"))
        self.pushButton_2.setText(_translate("PrincipalSimon", "INSTRUCCIONES"))
