# Form implementation generated from reading ui file 'c:\Users\aleva\OneDrive - Instituto Politecnico Nacional\Desktop\Documentos\Programing_Python\GUI\Calculadora\calculadora.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(427, 354)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\aleva\\OneDrive - Instituto Politecnico Nacional\\Desktop\\Documentos\\Programing_Python\\GUI\\Calculadora\\../../../../../../OneDrive/Imágenes/calculator.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 86, 255), stop:1 rgba(153, 153, 153, 255));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 280, 91, 31))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 63, 63, 255), stop:1 rgba(63, 63, 63, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 280, 41, 31))
        self.pushButton_2.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 280, 41, 31))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 219, 158);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"Bodoni MT Condensed\";\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 240, 41, 31))
        self.pushButton_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 63, 63, 255), stop:1 rgba(63, 63, 63, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 240, 41, 31))
        self.pushButton_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 63, 63, 255), stop:1 rgba(63, 63, 63, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(320, 240, 41, 31))
        self.pushButton_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 63, 63, 255), stop:1 rgba(63, 63, 63, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(370, 240, 41, 31))
        self.pushButton_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 123, 28);\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(270, 200, 41, 31))
        self.pushButton_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 63, 63, 255), stop:1 rgba(63, 63, 63, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(320, 200, 41, 31))
        self.pushButton_9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 63, 63, 255), stop:1 rgba(63, 63, 63, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(220, 200, 41, 31))
        self.pushButton_10.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 63, 63, 255), stop:1 rgba(63, 63, 63, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(270, 160, 41, 31))
        self.pushButton_11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 63, 63, 255), stop:1 rgba(63, 63, 63, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(320, 160, 41, 31))
        self.pushButton_12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 63, 63, 255), stop:1 rgba(63, 63, 63, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(220, 160, 41, 31))
        self.pushButton_13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(63, 63, 63, 255), stop:1 rgba(63, 63, 63, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(370, 200, 41, 31))
        self.pushButton_14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"background-color: rgb(255, 123, 28);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(370, 160, 41, 31))
        self.pushButton_15.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 24pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 123, 28);")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(370, 120, 41, 31))
        self.pushButton_16.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 18pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 123, 28);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(320, 120, 41, 31))
        self.pushButton_17.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"background-color: rgb(255, 0, 0);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(270, 120, 41, 31))
        self.pushButton_18.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"background-color: rgb(255, 123, 28);\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(220, 120, 41, 31))
        self.pushButton_19.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: rgb(255, 123, 28);\n"
"font: 20pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(150, 270, 51, 41))
        self.pushButton_20.setStyleSheet("background-color: rgb(255, 123, 28);\n"
"gridline-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(80, 270, 51, 41))
        self.pushButton_21.setStyleSheet("background-color: rgb(255, 123, 28);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 220, 51, 41))
        self.pushButton_22.setStyleSheet("background-color: rgb(255, 123, 28);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_22.setShortcut("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(80, 220, 51, 41))
        self.pushButton_23.setStyleSheet("background-color: rgb(255, 123, 28);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(150, 220, 51, 41))
        self.pushButton_24.setStyleSheet("background-color: rgb(255, 123, 28);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(10, 270, 51, 41))
        self.pushButton_25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 123, 28);\n"
"")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(10, 120, 51, 41))
        self.pushButton_26.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"selection-background-color: rgb(85, 0, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 123, 28);\n"
"")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_27.setGeometry(QtCore.QRect(10, 170, 51, 41))
        self.pushButton_27.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 123, 28);\n"
"")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_28.setGeometry(QtCore.QRect(80, 120, 51, 41))
        self.pushButton_28.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 123, 28);\n"
"")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_29.setGeometry(QtCore.QRect(150, 120, 51, 41))
        self.pushButton_29.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 123, 28);\n"
"")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_30.setGeometry(QtCore.QRect(80, 170, 51, 41))
        self.pushButton_30.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 123, 28);\n"
"\n"
"")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_31.setGeometry(QtCore.QRect(150, 170, 51, 41))
        self.pushButton_31.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(125, 125, 125, 255), stop:1 rgba(125, 125, 125, 255));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 16pt \"Bodoni MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 123, 28);\n"
"\n"
"")
        self.pushButton_31.setObjectName("pushButton_31")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 401, 71))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"Microsoft New Tai Lue\";")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 90, 401, 16))
        self.line.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 427, 22))
        self.menubar.setObjectName("menubar")
        self.menuCalculadora = QtWidgets.QMenu(parent=self.menubar)
        self.menuCalculadora.setObjectName("menuCalculadora")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCalculadora.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calcooladora"))
        self.pushButton.setText(_translate("MainWindow", "0"))
        self.pushButton.setShortcut(_translate("MainWindow", "0"))
        self.pushButton_2.setText(_translate("MainWindow", "."))
        self.pushButton_2.setShortcut(_translate("MainWindow", "."))
        self.pushButton_3.setText(_translate("MainWindow", "="))
        self.pushButton_4.setText(_translate("MainWindow", "1"))
        self.pushButton_4.setShortcut(_translate("MainWindow", "1"))
        self.pushButton_5.setText(_translate("MainWindow", "2"))
        self.pushButton_5.setShortcut(_translate("MainWindow", "2"))
        self.pushButton_6.setText(_translate("MainWindow", "3"))
        self.pushButton_6.setShortcut(_translate("MainWindow", "3"))
        self.pushButton_7.setText(_translate("MainWindow", "+"))
        self.pushButton_8.setText(_translate("MainWindow", "5"))
        self.pushButton_8.setShortcut(_translate("MainWindow", "5"))
        self.pushButton_9.setText(_translate("MainWindow", "6"))
        self.pushButton_9.setShortcut(_translate("MainWindow", "6"))
        self.pushButton_10.setText(_translate("MainWindow", "4"))
        self.pushButton_10.setShortcut(_translate("MainWindow", "4"))
        self.pushButton_11.setText(_translate("MainWindow", "8"))
        self.pushButton_11.setShortcut(_translate("MainWindow", "8"))
        self.pushButton_12.setText(_translate("MainWindow", "9"))
        self.pushButton_12.setShortcut(_translate("MainWindow", "9"))
        self.pushButton_13.setText(_translate("MainWindow", "7"))
        self.pushButton_13.setShortcut(_translate("MainWindow", "7"))
        self.pushButton_14.setText(_translate("MainWindow", "-"))
        self.pushButton_15.setText(_translate("MainWindow", "*"))
        self.pushButton_16.setText(_translate("MainWindow", "/"))
        self.pushButton_17.setText(_translate("MainWindow", "Help"))
        self.pushButton_18.setText(_translate("MainWindow", "Sqrt"))
        self.pushButton_19.setText(_translate("MainWindow", "Pi"))
        self.pushButton_20.setText(_translate("MainWindow", "e"))
        self.pushButton_21.setText(_translate("MainWindow", "ln"))
        self.pushButton_22.setText(_translate("MainWindow", "Sin"))
        self.pushButton_23.setText(_translate("MainWindow", "Cos"))
        self.pushButton_24.setText(_translate("MainWindow", "Tan"))
        self.pushButton_25.setText(_translate("MainWindow", "n!"))
        self.pushButton_26.setText(_translate("MainWindow", "C"))
        self.pushButton_27.setText(_translate("MainWindow", "AC"))
        self.pushButton_28.setText(_translate("MainWindow", "("))
        self.pushButton_29.setText(_translate("MainWindow", ")"))
        self.pushButton_30.setText(_translate("MainWindow", "x^2"))
        self.pushButton_31.setText(_translate("MainWindow", "x^-1"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:22pt;\">0</span></p></body></html>"))
        self.menuCalculadora.setTitle(_translate("MainWindow", "Calculadora"))
