# Form implementation generated from reading ui file 'c:\Users\aleva\OneDrive - Instituto Politecnico Nacional\Desktop\Documentos\Programing_Python\GUI\Botones\botones.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(299, 236)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boton_activar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.boton_activar.setGeometry(QtCore.QRect(20, 50, 81, 41))
        self.boton_activar.setObjectName("boton_activar")
        self.boton_desactivar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.boton_desactivar.setGeometry(QtCore.QRect(20, 120, 81, 41))
        self.boton_desactivar.setObjectName("boton_desactivar")
        self.etiqueta = QtWidgets.QLabel(parent=self.centralwidget)
        self.etiqueta.setGeometry(QtCore.QRect(150, 80, 91, 41))
        self.etiqueta.setText("")
        self.etiqueta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.etiqueta.setObjectName("etiqueta")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 299, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.boton_activar.setText(_translate("MainWindow", "Activar"))
        self.boton_desactivar.setText(_translate("MainWindow", "Desactivar"))
